### ISSUE TITLE
Nice-to-have

### ISSUE THREAD

**Issue by hallabro** [89netraM/iMat#24]
- [x] Dölj kortnummer
- [ ] Ta fram kortttyp (MasterCard/Visa) från kortnummer
- [x] Dölja kategoripilarna i nederkanten efter man har sökt fram produkter

**Comment by 89netraM** [comment]
> * Ta fram kortttyp (MasterCard/Visa) från kortnummer

@Rotanator vill du ta den samtidigt om du ändå skulle ta valideringen?

**Comment by Rotanator** [comment]
@89netraM visst, inga problem!

**Comment by hallabro** [comment]
Good times! :smile:  Stänger så de inte tar upp plats i mina issues.
