### ISSUE TITLE
Vyn för alla produkter

### ISSUE THREAD

**Issue by johangottlander** [89netraM/iMat#36]
Märkte att när man söker utan att skriva in något så visas två stycken produkter horisontellt, istället för tre stycken.

**Comment by 89netraM** [comment]
Underligt, det gör det inte för mig. Kan det vara MAC/PC? Om du vill kolla på det kan du ställa ner `maxWidth` på elementen genom att ändra på rad 44 i `QProductListItemComponent.fxml`.

![](https://i.imgur.com/s9Is3eM.png)

**Comment by hallabro** [comment]
Jag har tre produkter på min maskin också (Windows). :thinking:

**Comment by johangottlander** [comment]
Fungerar för mig med nu, riktigt snyggt med en progress indicator också. Märkte den först nu (y).

**Comment by hallabro** [comment]
Japp, den kommer från https://github.com/89netraM/iMat/commit/af01da6f1cd660d751186457a578446b5f3a80eb. @89netraM lagt till en massa balla grejjer. :tada:

**Comment by hallabro** [comment]
Stänger denna då det inte verkar vara något problem längre.
