### ISSUE TITLE
Vald kategori i karusell vid start

### ISSUE THREAD

**Issue by hallabro** [89netraM/iMat#39]
@89netraM @johangottlander @Rotanator 

Jag minns inte riktigt hur vi resonerade med kategorikarusellen. 

Skulle man starta med kategorin längst till vänster i karusellen och gå en genom "avdelning" i taget?

Estetiskt ser det ju mycket bättre ut om man börjar med att markera mitten-kategorin när man startar.
![Untitled](https://user-images.githubusercontent.com/44033026/58758782-d295ef80-8520-11e9-977b-9c2fb8d66c79.png)

**Comment by 89netraM** [comment]
Jag tycker fortfarande att den ska börja i början. Då tror jag det blir lättare att veta när man gått igenom hela.

**Comment by hallabro** [comment]
:+1: Då tycker jag vi fortsätter så.
